# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170608_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesubtype',
            old_name='subservicetype_text',
            new_name='servicesubtype_text',
        ),
    ]
