# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170608_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubtype',
            name='category',
            field=models.CharField(blank=True, choices=[('Agar', 'Agar'), ('Antibiotics', 'Antibiotics'), ('Dextrose Food', 'Dextrose Food'), ('Liquid Media', 'Liquid Media'), ('Miscellaneous', 'Micellaneous'), ('Power Food', 'Power Food'), ('Solutions & Buffers', 'Solutions & Buffers'), ('Standard Food', 'Standard Food'), ('Sylgard', 'Sylgard'), ('Wurzburg Food', 'Wurzburg Food')], default='Miscellaneous', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicesubtype',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicesubtype',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesubtype',
            name='jm_category',
            field=models.CharField(blank=True, choices=[('labor', 'labor'), ('equipment', 'equipment'), ('materials', 'materials'), ('service', 'service'), ('sample', 'sample')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicesubtype',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicesubtype',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicesubtype',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
