# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170613_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Vendor'),
        ),
    ]
