# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20170710_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='volume',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
