# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20170912_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two')], default='One', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='media_type',
            field=models.CharField(blank=True, choices=[('Agar', 'Agar'), ('Antibiotics', 'Antibiotics'), ('Cornmeal Food', 'Fly Food - Cornmeal'), ('Dextrose Food', 'Fly Food - Dextrose'), ('Power Food', 'Fly Food - Power'), ('Wurzburg Food', 'Fly Food - Wurzburg'), ('Liquid Media', 'Liquid Media'), ('Miscellaneous', 'Miscellaneous'), ('Solutions & Buffers', 'Solutions & Buffers'), ('Sylgard', 'Sylgard')], max_length=30, null=True),
        ),
    ]
