# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20170927_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_recurring_start',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('In_Progress', 'In Progress'), ('Complete', 'Complete'), ('Canceled', 'Canceled'), ('Problem', 'Problem')], default='Problem', max_length=30),
        ),
    ]
