# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20171010_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='cost',
            new_name='line_cost',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='store.Order'),
        ),
    ]
