# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20171011_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Submitted'), ('2', 'In Progress'), ('3', 'Complete'), ('4', 'Canceled'), ('5', 'Problem')], default='Problem', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order'),
        ),
    ]
