# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 09:49
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('store', '0027_auto_20171114_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFullName',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Canceled', 'Canceled'), ('Problem', 'Problem'), ('Auto', 'Auto'), ('Billed', 'Billed')], default='Problem', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='inventory',
            field=models.ForeignKey(default=610, on_delete=django.db.models.deletion.CASCADE, to='store.Inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
