# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20180131_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('2W.225', '2W.225 (4C)'), ('2W.227', '2W.227 (4C)'), ('2W.263', '2W.263 (4C)'), ('2W.265', '2W.265 (4C)'), ('2C.225', '2C.225 (4C)'), ('2C.227', '2C.227 (4C)'), ('2C.267', '2C.267 (4C)'), ('2C.277', '2C.277 (4C)'), ('2E.231', '2E.231 (4C)'), ('2E.233', '2E.233 (18C)'), ('2E.267', '2E.267 (4C)'), ('3W.228', '3W.228 (4C)'), ('3W.266', '3W.266 (4C)'), ('3C.226', '3C.226 (4C)'), ('3C.229', '3C.229 (18C)'), ('3C.265', '3C.265 (4C)'), ('3C.267', '3C.267 (4C)'), ('3E.265', '3E.265 (18C)'), ('3E.267', '3E.267 (4C)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Canceled', 'Canceled'), ('Problem', 'Problem'), ('Auto', 'Auto'), ('Billed', 'Billed')], default='Submitted', max_length=30),
        ),
    ]
