# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-05 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20180307_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_manager',
        ),
    ]
