# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20180605_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offboard_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skip_updates',
            field=models.BooleanField(default=False),
        ),
    ]
