# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_userprofile_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
