# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20180606_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='part_num',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_modified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
