# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20180606_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='notes',
            new_name='notes_inv',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='notes',
            new_name='notes_ven',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='unit',
        ),
        migrations.AddField(
            model_name='order',
            name='notes_order',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
