# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20180614_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='store.Department'),
            preserve_default=False,
        ),
    ]
