# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20180614_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days_since_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
