# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20180710_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recur_stop_email',
            field=models.BooleanField(default=False),
        ),
    ]
