# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_order_recur_stop_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='recur_stop_email',
        ),
    ]
