# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-16 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_department_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
