# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20180716_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
