# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20180726_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcode', to='store.UserProfile'),
        ),
    ]
