# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-04 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_order_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weeks',
            field=models.CharField(blank=True, choices=[('1', 'week'), ('2', '2 weeks'), ('3', '3 weeks'), ('4', 'once a month')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('2W.225', '2W.225 (4C)'), ('2W.227', '2W.227 (4C)'), ('2W.263', '2W.263 (4C)'), ('2W.265', '2W.265 (4C)'), ('2C.225', '2C.225 (4C)'), ('2C.227', '2C.227 (4C)'), ('2C.267', '2C.267 (4C)'), ('2C.277', '2C.277 (4C)'), ('2C ambient', 'Near 2C.243 (21C)'), ('2E.231', '2E.231 (4C)'), ('2E.233', '2E.233 (18C)'), ('2E.267', '2E.267 (4C)'), ('2E.336.1', 'Robot Room (21C)'), ('3W.228', '3W.228 (4C)'), ('3W.266', '3W.266 (4C)'), ('3C.226', '3C.226 (4C)'), ('3C.229', '3C.229 (18C)'), ('3C.265', '3C.265 (4C)'), ('3C.267', '3C.267 (4C)'), ('3C ambient', 'Near 3C.289 (21C)'), ('3E.265', '3E.265 (18C)'), ('3E.267', '3E.267 (4C)')], max_length=30),
        ),
    ]
