# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_auto_20181004_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottles_Vials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amnt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Inventory')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='weeks',
            field=models.CharField(blank=True, choices=[('1', 'every week'), ('2', 'every 2 weeks'), ('3', 'every 3 weeks'), ('4', 'once a month')], max_length=30, null=True),
        ),
    ]
