<<<<<<< HEAD:store/migrations/0052_auto_20190703_1550.py
# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_auto_20190320_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-23 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_auto_20190320_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
>>>>>>> bb903bd2b21088b5be96ff1bda8313bd6165e24a:store/migrations/0052_auto_20190823_1407.py
