# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-05 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import visitor_project_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'tracker_otherhost',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Project Code')),
                ('department_code', models.CharField(blank=True, help_text='A Janelia department code such as 093060', max_length=20, verbose_name='Department Number')),
                ('programmatic', models.BooleanField()),
                ('status', models.CharField(choices=[('AWAITINGREVIEW', 'Awaiting Review'), ('PENDING', 'Pending'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='AWAITINGREVIEW', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Uncheck when this project is no longer active')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('overview_benefits', models.TextField(blank=True)),
                ('overview_costs', models.TextField(blank=True)),
                ('deadline_operations_reviews', models.DateField(blank=True, default=visitor_project_tracker.models.Project.default_deadline, help_text='Default deadline to use for operations reviews', null=True)),
                ('deadline_labhead_reviews', models.DateField(blank=True, default=visitor_project_tracker.models.Project.default_deadline, help_text='Default deadline to use for scientific reviews', null=True)),
                ('seminar_location', models.CharField(blank=True, max_length=100)),
                ('seminar_datetime', models.DateTimeField(blank=True, null=True)),
                ('budget_personnel', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('budget_shared_resources', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('budget_supplies', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('budget_travel', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('budget_housing', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('budget_IT', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('budget_equipment_non_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('budget_other', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('budget_equipment_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('resources_personnel', models.TextField(blank=True)),
                ('resources_lab_space', models.TextField(blank=True)),
                ('resources_shared_resources', models.TextField(blank=True)),
                ('resources_safety_animals', models.TextField(blank=True)),
                ('resources_lab_supplies', models.TextField(blank=True)),
                ('resources_travel', models.TextField(blank=True)),
                ('resources_housing', models.TextField(blank=True)),
                ('resources_IT', models.TextField(blank=True, verbose_name='Resources IT')),
                ('resources_equipment_non_capital', models.TextField(blank=True)),
                ('resources_equipment_capital', models.TextField(blank=True)),
                ('resources_other', models.TextField(blank=True)),
                ('resources_comments', models.TextField(blank=True)),
                ('publication_plan', models.TextField(blank=True)),
                ('proposed_title', models.CharField(max_length=200)),
                ('application_form', models.FileField(blank=True, help_text="Uploading an application form will prepopulate the fields below after saving (if they are empty.) If this is a renewal please set the 'Renewal of' field below BEFORE adding the application. (or make sure the prhase 'renew' is in the file name.)", upload_to='uploads', verbose_name='Submitted Application')),
                ('proposed_problem', models.TextField(blank=True)),
                ('proposed_solution', models.TextField(blank=True)),
                ('proposed_outcome', models.TextField(blank=True)),
                ('proposed_time_frame', models.TextField(blank=True)),
                ('proposed_collaboration', models.TextField(blank=True)),
                ('proposed_appropriateness', models.TextField(blank=True)),
                ('progress', models.TextField(blank=True, help_text='for renewals', verbose_name='Summary of progress')),
                ('work_done_at_janelia', models.TextField(blank=True, help_text='for renewals', verbose_name='Description of work done at Janelia')),
                ('work_done_at_vistitors_institution', models.TextField(blank=True, help_text='for renewals', verbose_name="Description of work done at the visitor's institution(s)")),
                ('scope', models.TextField(blank=True, help_text='for renewals')),
            ],
            options={
                'managed': False,
                'db_table': 'tracker_project',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Project Code')),
                ('department_code', models.CharField(blank=True, help_text='A Janelia department code such as 093060', max_length=20, verbose_name='Department Number')),
                ('comment', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'managed': False,
                'db_table': 'tracker_teamproject',
            },
        ),
        migrations.CreateModel(
            name='VisitingScientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, choices=[('HHMIINVESTIGATOR', 'HHMI Investigator'), ('HHMIEARLYCAREERSCIENTIST', 'HHMI Early Career Scientist'), ('PRINCIPALINVESTIGATOR', 'Principal Investigator'), ('POSTDOCTORALFELLOW', 'Postdoctoral Fellow'), ('GRADUATESTUDENT', 'Graduate Student'), ('UNDERGRADUATESTUDENT', 'Undergraduate Student'), ('OTHER', 'Other (specify)')], max_length=50)),
                ('title_if_other', models.CharField(blank=True, help_text='Enter title here is it is not one of the choices', max_length=100)),
                ('appointment_start_date', models.DateField(blank=True, null=True)),
                ('appointment_end_date', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('institute', models.CharField(blank=True, max_length=500, verbose_name='Institution')),
                ('address_1', models.CharField(blank=True, max_length=35)),
                ('address_2', models.CharField(blank=True, help_text='Suite Number, Mail Stop, Department', max_length=35)),
                ('city_state_zip', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=500)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=100)),
                ('CV', models.FileField(blank=True, upload_to='uploads')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tracker_visitingscientist',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='VisitorProgramTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email Address')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
    ]
